Revert command subsystem
This reverts commit 156f7b3de56ba3a4e5e225dd0d7076dc22db0bf5.
This reverts commit c95e0bfd420ddae404660b98314a2b15ac2867c8.
This reverts commit 4bbbeb317583eee47ed2b40c380ca44be60f56e6.
This reverts commit 0151d75e81327b7a3433834137d96731787544e0.
This reverts commit 367c74dbba56b0a91d425be5f362a0df79f98acf.

Fixes MERGIFY-ENGINE-Y4
Fixes MERGIFY-ENGINE-Y7
Fixes MERGIFY-ENGINE-Y5

This broke the `mergify-debug` command load at least due to an import loop:

>>> import mergify_engine.actions.merge.action
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2419, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'mergify_engine.actions.merge.action' has no attribute 'MergeAction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/mergify_engine/actions/merge/action.py", line 25, in <module>
    from mergify_engine.actions.merge import queue
  File "/app/mergify_engine/actions/merge/queue.py", line 25, in <module>
    from mergify_engine.worker import app
  File "/app/mergify_engine/worker.py", line 76, in <module>
    import mergify_engine.tasks.github_events  # noqa
  File "/app/mergify_engine/tasks/github_events.py", line 23, in <module>
    from mergify_engine.tasks import engine
  File "/app/mergify_engine/tasks/engine/__init__.py", line 20, in <module>
    from mergify_engine import rules
  File "/app/mergify_engine/rules/__init__.py", line 63, in <module>
    for ep in pkg_resources.iter_entry_points("mergify_actions")
  File "/app/mergify_engine/rules/__init__.py", line 63, in <genexpr>
    for ep in pkg_resources.iter_entry_points("mergify_actions")
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2421, in resolve
    raise ImportError(str(exc))
ImportError: module 'mergify_engine.actions.merge.action' has no attribute 'MergeAction'